CREATE DATABASE IF NOT EXISTS mydb;
USE mydb;

CREATE TABLE IF NOT EXISTS key_value_pair (
    id INT AUTO_INCREMENT PRIMARY KEY,
    `key` VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL UNIQUE,
    `value` VARCHAR(255) CHARACTER SET utf8mb4
);
